sevir: &sevir
  type: sevir_latent
  input_length: &input_length 13 
  pred_length: &pred_length 12
  total_length: &total_length 25
  base_freq: 5min
  data_dir: radar:s3://sevir_latent ## path/to/sevir
  latent_gt_dir: /mnt/petrelfs/xukaiyi/CodeSpace/CasCast/latent_data
  latent_deterministic_dir: path/to/latent_prediction

  latent_size: 32x32x1

dataset:
  train:
    <<: *sevir

  valid:
    <<: *sevir

sampler:
  type: TrainingSampler

dataloader:
  num_workers: 16 
  pin_memory: False
  prefetch_factor: 2
  persistent_workers: True

trainer:
  batch_size: 16
  valid_batch_size: 1
  max_epoch: &max_epoch 1
  max_step: 1000000

model:
  type: latent_diffusion_model
  params:
    diffusion_kwargs:
        noise_scheduler:
          DDPMScheduler:
            num_train_timesteps: &num_classes 2000
            beta_start: &sigma_start 0.0001
            beta_end: &sigma_end 0.02
            beta_schedule: &sigma_dist linear
            clip_sample_range: 13
            prediction_type: epsilon
        classifier_free_guidance:
          p_uncond: 0.1
          guidance_weight: 1 ## TODO

    sub_model:
      unet: 
        in_channel: 10
        out_channel: 1
        inner_channel: 64
        channel_multiplier: [1, 2, 2]
        attn_res: [16]
        res_blocks: 2
        dropout: 0.2
        image_size: 32
        cond_channel: 9
        
      autoencoder_kl:
        in_channels: 1
        out_channels: 1
        down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
        up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
        block_out_channels: [128, 256, 512, 512]
        layers_per_block: 2
        latent_channels: 1
        norm_num_groups: 32


    save_best: &loss_type MSE
    use_ceph: False
    ceph_checkpoint_path: "mpas:s3://sevir/checkpoint"
    metrics_type: None
    data_type: fp32

    visualizer:
      visualizer_type: sevir_visualizer
      visualizer_step: 4000

    optimizer:
      unet:
        type: AdamW
        params:
          lr: 0.0005
          betas: [0.9, 0.95]
          # eps: 0.000001
      
    lr_scheduler:
      unet:
        by_step: True
        sched: cosine
        epochs: *max_epoch
        min_lr: 0.00001
        warmup_lr: 0.00001
        warmup_epochs: 0.1
        lr_noise: 
        cooldown_epochs: 0

    extra_params:
      loss_type: MSELoss
      enabled_amp: False
      log_step: 20
      predictor_checkpoint_path: None ## for pretrained advective predictor
      autoencoder_checkpoint_path: /mnt/petrelfs/xukaiyi/CodeSpace/DiT/ckpt/ae_checkpoint_latest.pth
      save_epoch_interval: 20

    # wandb:
    #   project_name: sevir